# Generated by Django 3.2.3 on 2021-12-15 09:50

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
